---
title: Quarto installation
---

Quarto is simply downloaded from the [quarto website](https://quarto.org/docs/get-started/).

### Windows
On Windows, simply download the `quarto-< version >.msi` and install quarto from the msi.

Just like git, quarto has to be added to path in order for application and the terminal to find it.
This done via the 'environment variables' screen.

Once added check if it's correctly installed via:
```bash
quarto --version
# or
quarto check
```

### Linux
On linux there are two options:

- Installing from a debian package
- Installing from a tar archive

First we will look at a debian package, which is only applicable to Debian/ Ubuntu.

The first thing that is needed is `gdebi-core`. Without this package debian packages cannot be installed.

Installed this package via:
```bash
sudo apt install gdebi-core
```

Now download quarto as a the debian package:
```bash
wget < link to package >
```

Install the debian package:
```bash
sudo gdebi < path to package >
```

Verify the installation:
```bash
quarto --version
# or
quarto check
```

Now via a tar archive.
::: {.callout-note}
Make sure this is within a directory that make sense for the application to be. E.g. `< home >/apps`
:::

Down the archive:
```bash
wget < link to tar archive >
```

Unpack the archive using `tar`:
```bash
tar -xvzf < path to archive >
```

To add it to path type the following commands:
```bash
# Go to the home directory
cd
# Create a bin dir (if not there)
mkdir bin
# create a simlink
ln -s < path to git binary > ~/bin/git
# Add bin directory to path (if not already done)
( echo ""; echo 'export PATH=$PATH:~/bin\n' ; echo "" ) >> ~/.profile
source ~/.profile
```

Now again check the installation:
```bash
quarto --version
# or
quarto check
```
