name: up2020

channels:
- conda-forge

dependencies:
- graphviz # Visualizing DAG images
- hydromt>=0.9.4 # most recent and stable release
- hydromt_wflow>=0.5.0
- hydromt_sfincs>=1.0.3
- jupyter
- matplotlib
- nc-time-axis
- openpyxl # Not quite sure if we need this driver
- pip
- pre-commit
- python=3.11.*
- pip:
  - pulp==2.7.0 # Making DAG's work
  - snakemake==7.32.4 # Snakemake 8.x.x sucks
