name: hydroflows

channels:
- conda-forge

dependencies:
- flit
- graphviz
- hydromt>=0.9.4
- hydromt_sfincs
- hydromt_wflow
- jupyter
- matplotlib
- nbsphinx
- numpy>=1.20
- pip>=23.1.2
- pre-commit
- pydantic
- pydata-sphinx-theme
- pytest-cov
- pytest-lazy-fixture
- pytest-mock
- pytest-timeout
- pytest>=2.7.3
- ruff
- sphinx
- tomli
- tomli-w
- twine
- xugrid
- pip:
  - hydromt_fiat@git+ssh://git@github.com/Deltares/hydromt_fiat.git
  - pulp==2.7.0
  - snakemake==7.32.4
  - sphinx_design
