setup_region:
  region:
    geom: <region> # placeholder for region vector file

setup_output:
  output_dir: output
  output_csv_name: output.csv
  output_vector_name: spatial.gpkg

setup_vulnerability:
  vulnerability_fn: jrc_vulnerability_curves
  vulnerability_identifiers_and_linking_fn: jrc_vulnerability_curves_linking
  unit: meters
  continent: Europe

setup_exposure_buildings:
  asset_locations: OSM
  occupancy_type: OSM
  max_potential_damage: jrc_damage_values
  ground_floor_height: 0
  unit: "meters"
  extraction_method: centroid
  country: "Italy"

setup_exposure_roads:
  roads_fn: "OSM"
  road_types: ["motorway", "primary", "secondary", "tertiary"]
  road_damage: null
  unit: "meters"
