setup_global_settings:
  keep_temp_files: True

setup_region:

setup_output:
  output_dir: output
  output_csv_name: output.csv
  output_vector_name: spatial.gpkg

setup_vulnerability:
  vulnerability_fn: jrc_vulnerability_curves
  vulnerability_identifiers_and_linking_fn: jrc_vulnerability_curves_linking
  unit: m
  continent: Africa

setup_exposure_buildings:
  asset_locations: OSM
  occupancy_type: OSM
  max_potential_damage: jrc_damage_values
  ground_floor_height: 0
  unit: m
  extraction_method: centroid
  damage_types: ["structure", "content"]
  country: "Nigeria"
