setup_config:
  starttime: "2010-01-01T00:00:00"
  endtime: "2010-03-31T00:00:00"
  timestepsecs: 86400
  input.path_forcing: inmaps-era5-2010.nc

setup_basemaps:
  region: <region> # placeholder for model region
  res: <res>, # Placeholder for model resolution
  hydrography_fn: merit_hydro,
  basin_index_fn: merit_hydro_index,
  upscale_method: ihu

setup_rivers:
  hydrography_fn: merit_hydro
  river_geom_fn: rivers_lin2019_v1
  river_upa: 30
  rivdph_method: powlaw
  min_rivdph: 1
  min_rivwth: 30
  slope_len: 2e3
  smooth_len: 5e3
  elevtn_map: dem_subgrid
  river_routing: local-inertial

setup_floodplains:
  floodplain_type: 1d
  hydrography_fn: merit_hydro

setup_reservoirs:
  reservoirs_fn: hydro_reservoirs
  min_area: 1.0
  priority_jrc: True

setup_lakes:
  lakes_fn: hydro_lakes
  min_area: 10.0

setup_glaciers:
  glaciers_fn: rgi
  min_area: 1

setup_lulcmaps:
  lulc_fn: globcover

setup_laimaps:
  lai_fn: modis_lai

setup_soilmaps:
  soil_fn: soilgrids
  ptf_ksatver: brakensiek

setup_outlets:
  river_only: True

setup_constant_pars:
  KsatHorFrac: 100
  Cfmax: 3.75653
  cf_soil: 0.038
  EoverR: 0.11
  InfiltCapPath: 5
  InfiltCapSoil: 600
  MaxLeakage: 0
  rootdistpar: -500
  TT: 0
  TTI: 2
  TTM: 0
  WHC: 0.1
  G_Cfmax: 5.3
  G_SIfrac: 0.002
  G_TT: 1.3
