catalog_path_global: c:/Users/rautenba/repos/HydroFlows/cases/Rio/data/global-data/data_catalog.yml
catalog_path_local: c:/Users/rautenba/repos/HydroFlows/cases/Rio/data/local-data/data_catalog.yml
depth_min: 0.05
end_date: '2023-12-31'
fiat_build_fiat_root: models/fiat
fiat_prep_exposure_script: c:/Users/rautenba/repos/HydroFlows/cases/Rio/scripts/prepare_exposure_files.py
fiat_exe: c:/Users/rautenba/repos/HydroFlows/cases/Rio/bin/fiat_v0.2.1/fiat.exe
fiat_preprocess_exposure_script: c:/Users/rautenba/repos/HydroFlows/cases/Rio/scripts/preprocess_exposure.py
floodadapt_build_output_dir: models/flood_adapt_builder
hydromt_fiat_config: c:/Users/rautenba/repos/HydroFlows/cases/Rio/setups/local/hydromt_config/fiat_config.yml
hydromt_sfincs_config: c:/Users/rautenba/repos/HydroFlows/cases/Rio/setups/local/hydromt_config/sfincs_config.yml
plot_fig: true
pluvial_design_events_event_root: events/design
pluvial_design_events_wildcard: pluvial_design_events
preprocess_local_rainfall_script: c:/Users/rautenba/repos/HydroFlows/cases/Rio/scripts/preprocess_local_precip.py
region: c:/Users/rautenba/repos/HydroFlows/cases/Rio/data/region.geojson
risk: true
rps:
- 5
- 10
- 100
sfincs_build_sfincs_root: models/sfincs
sfincs_downscale_output_root: output/hazard
sfincs_exe: c:/Users/rautenba/repos/HydroFlows/cases/Rio/bin/sfincs_v2.1.1/sfincs.exe
start_date: '1990-01-01'
