"""The methods to register."""

__eps__ = {
    "climate_change_factors": "hydroflows.climate.change_factor:ClimateChangeFactors",
    "monthly_climatology": "hydroflows.climate.climatology:MonthlyClimatology",
    "merge_gridded_datasets": "hydroflows.raster.merge:MergeGriddedDatasets",
    "fiat_run": "hydroflows.fiat.fiat_run:FIATRun",
    "fiat_build": "hydroflows.fiat.fiat_build:FIATBuild",
    "fiat_update_hazard": "hydroflows.fiat.fiat_update:FIATUpdateHazard",
    "fiat_visualize": "hydroflows.fiat.fiat_visualize:FIATVisualize",
    "get_ERA5_rainfall": "hydroflows.rainfall.get_ERA5_rainfall:GetERA5Rainfall",
    "pluvial_design_events": "hydroflows.rainfall.pluvial_design_events:PluvialDesignEvents",
    "pluvial_design_events_GPEX": "hydroflows.rainfall.pluvial_design_events_GPEX:PluvialDesignEventsGPEX",
    "future_climate_rainfall": "hydroflows.rainfall.future_climate_rainfall:FutureClimateRainfall",
    "sfincs_region": "hydroflows.sfincs.sfincs_region:SfincsRegion",
    "sfincs_build": "hydroflows.sfincs.sfincs_build:SfincsBuild",
    "sfincs_run": "hydroflows.sfincs.sfincs_run:SfincsRun",
    "sfincs_postprocess": "hydroflows.sfincs.sfincs_postprocess:SfincsPostprocess",
    "sfincs_downscale": "hydroflows.sfincs.sfincs_downscale:SfincsDownscale",
    "sfincs_update_forcing": "hydroflows.sfincs.sfincs_update_forcing:SfincsUpdateForcing",
    "wflow_build": "hydroflows.wflow.wflow_build:WflowBuild",
    "wflow_run": "hydroflows.wflow.wflow_run:WflowRun",
    "wflow_update_factors": "hydroflows.wflow.wflow_update_factors:WflowUpdateChangeFactors",
    "wflow_update_forcing": "hydroflows.wflow.wflow_update_forcing:WflowUpdateForcing",
    "coastal_design_events": "hydroflows.coastal.coastal_design_events:CoastalDesignEvents",
    "coastal_design_events_from_rp_data": "hydroflows.coastal.coastal_design_events_from_rp_data:CoastalDesignEventFromRPData",
    "coastal_tidal_analysis": "hydroflows.coastal.coastal_tidal_analysis:CoastalTidalAnalysis",
    "future_slr": "hydroflows.coastal.future_slr:FutureSLR",
    "get_coast_rp": "hydroflows.coastal.get_coast_rp:GetCoastRP",
    "get_gtsm_data": "hydroflows.coastal.get_gtsm_data:GetGTSMData",
    "floodmarks_validation": "hydroflows.hazard_validation.floodmarks:FloodmarksValidation",
    "fluvial_design_events": "hydroflows.discharge.fluvial_design_events:FluvialDesignEvents",
    "setup_flood_adapt": "hydroflows.flood_adapt.setup_flood_adapt:SetupFloodAdapt",
    "merge_catalogs": "hydroflows.catalog.merge_catalogs:MergeCatalogs",
    "historical_events": "hydroflows.historical_events.historical_events:HistoricalEvents",
    "combine_dummy_events": "hydroflows.dummy.combine_dummy_events:CombineDummyEvents",
    "prepare_dummy_events": "hydroflows.dummy.prepare_dummy_events:PrepareDummyEvents",
    "run_dummy_event": "hydroflows.dummy.run_dummy_event:RunDummyEvent",
    "postprocess_dummy_event": "hydroflows.dummy.postprocess_dummy_event:PostprocessDummyEvent",
    "prep_sfincs_models": "hydroflows.flood_adapt.prep_sfincs_models:PrepSfincsModels",
}
