blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/Deltares-Research/HydroFlows/discussions
    about: Ask questions and discuss with other community members
