Charts:
  Homes:
    Name: "Homes"
  Businesses:
    Name: "Businesses"
  Health:
    Name: "Health facilities"
  Schools:
    Name: "Schools"
  Emergency:
    Name: "Emergency facilities"

Categories:
  Minor:
    Name: "Minor"
    Color: "#ffa500"
  Major:
    Name: "Major"
    Color: "#ff0000"
  Destroyed:
    Name: "Destroyed"
    Color: "#000000"

Slices:
  Minor_Homes:
    Name: "Minor Homes"
    Query: "ResidentialMinorCount"
    Chart: "Homes"
    Category: "Minor"
  Major_Homes:
    Name: "Major Homes"
    Query: "ResidentialMajorCount"
    Chart: "Homes"
    Category: "Major"
  Destroyed_Homes:
    Name: "Destroyed Homes"
    Query: "ResidentialDestroyedCount"
    Chart: "Homes"
    Category: "Destroyed"
  Minor_Businesses:
    Name: "Minor Businesses"
    Query: "CommercialMinorCount"
    Chart: "Businesses"
    Category: "Minor"
  Major_Businesses:
    Name: "Major Businesses"
    Query: "CommercialMajorCount"
    Chart: "Businesses"
    Category: "Major"
  Destroyed_Businesses:
    Name: "Destroyed Businesses"
    Query: "CommercialDestroyedCount"
    Chart: "Businesses"
    Category: "Destroyed"
  Minor_Health:
    Name: "Minor Health"
    Query: "HealthMinorCount"
    Chart: "Health facilities"
    Category: "Minor"
  Major_Health:
    Name: "Major Health"
    Query: "HealthMajorCount"
    Chart: "Health facilities"
    Category: "Major"
  Destroyed_Health:
    Name: "Destroyed Health"
    Query: "HealthDestroyedCount"
    Chart: "Health facilities"
    Category: "Destroyed"
  Minor_Schools:
    Name: "Minor Schools"
    Query: "SchoolsMinorCount"
    Chart: "Schools"
    Category: "Minor"
  Major_Schools:
    Name: "Major Schools"
    Query: "SchoolsMajorCount"
    Chart: "Schools"
    Category: "Major"
  Destroyed_Schools:
    Name: "Destroyed Schools"
    Query: "SchoolsDestroyedCount"
    Chart: "Schools"
    Category: "Destroyed"
  Minor_Emergency:
    Name: "Minor Emergency"
    Query: "EmergencyMinorCount"
    Chart: "Emergency facilities"
    Category: "Minor"
  Major_Emergency:
    Name: "Major Emergency"
    Query: "EmergencyMajorCount"
    Chart: "Emergency facilities"
    Category: "Major"
  Destroyed_Emergency:
    Name: "Destroyed Emergency"
    Query: "EmergencyDestroyedCount"
    Chart: "Emergency facilities"
    Category: "Destroyed"

Other:
  Plot:
    numbers_font: 20
    height: 350
    width: 1200
  Title:
    text: "Building damage"
    font: 30
  Subtitle:
    font: 25
  Legend:
    font: 20
  Info:
    text: |
      Thresholds:<br>
      Minor: <= 1 feet<br>
      Major: > 1 and <= 6 feet<br>
      Destroyed: > 6 feet<br>
    scale: 0.1
