aggregateBy = [
    "Neighbourhood",
]

[[queries]]
name = "ExpectedAnnualDamages"
description = "Expected annual damages"
select = "SUM(`Risk (EAD)`)"
filter = ""
long_name = "Expected Annual Damages"
show_in_metrics_table = "True"

[[queries]]
name = "TotalDamageRP1"
description = "Total damage with return period of 1 years"
select = "SUM(`Total Damage (1Y)`)"
filter = ""
long_name = "Total Damage (RP 1)"
show_in_metrics_table = "True"

[[queries]]
name = "TotalDamageRP2"
description = "Total damage with return period of 2 years"
select = "SUM(`Total Damage (2Y)`)"
filter = ""
long_name = "Total Damage (RP 2)"
show_in_metrics_table = "True"

[[queries]]
name = "TotalDamageRP5"
description = "Total damage with return period of 5 years"
select = "SUM(`Total Damage (5Y)`)"
filter = ""
long_name = "Total Damage (RP 5)"
show_in_metrics_table = "True"

[[queries]]
name = "TotalDamageRP10"
description = "Total damage with return period of 10 years"
select = "SUM(`Total Damage (10Y)`)"
filter = ""
long_name = "Total Damage (RP 10)"
show_in_metrics_table = "True"

[[queries]]
name = "TotalDamageRP25"
description = "Total damage with return period of 25 years"
select = "SUM(`Total Damage (25Y)`)"
filter = ""
long_name = "Total Damage (RP 25)"
show_in_metrics_table = "True"

[[queries]]
name = "TotalDamageRP50"
description = "Total damage with return period of 50 years"
select = "SUM(`Total Damage (50Y)`)"
filter = ""
long_name = "Total Damage (RP 50)"
show_in_metrics_table = "True"

[[queries]]
name = "TotalDamageRP100"
description = "Total damage with return period of 100 years"
select = "SUM(`Total Damage (100Y)`)"
filter = ""
long_name = "Total Damage (RP 100)"
show_in_metrics_table = "True"

[[queries]]
name = "ImpactedHomes2Y"
description = "Number of residential buildings with return period of 2 years"
select = "COUNT(*)"
filter = "`Primary Object Type` IN ('residential') AND `Total Damage (2Y)` > 0"
long_name = "Flooded homes (2Y)"
show_in_metrics_table = "True"

[[queries]]
name = "ImpactedHomes5Y"
description = "Number of residential buildings with return period of 5 years"
select = "COUNT(*)"
filter = "`Primary Object Type` IN ('residential') AND `Total Damage (5Y)` > 0"
long_name = "Flooded homes (5Y)"
show_in_metrics_table = "True"

[[queries]]
name = "ImpactedHomes10Y"
description = "Number of residential buildings with return period of 10 years"
select = "COUNT(*)"
filter = "`Primary Object Type` IN ('residential') AND `Total Damage (10Y)` > 0"
long_name = "Flooded homes (10Y)"
show_in_metrics_table = "True"

[[queries]]
name = "ImpactedHomes25Y"
description = "Number of residential buildings with return period of 25 years"
select = "COUNT(*)"
filter = "`Primary Object Type` IN ('residential') AND `Total Damage (25Y)` > 0"
long_name = "Flooded homes (25Y)"
show_in_metrics_table = "True"

[[queries]]
name = "ImpactedHomes50Y"
description = "Number of residential buildings with return period of 50 years"
select = "COUNT(*)"
filter = "`Primary Object Type` IN ('residential') AND `Total Damage (50Y)` > 0"
long_name = "Flooded homes (50Y)"
show_in_metrics_table = "True"


[[queries]]
name = "ImpactedHomes100Y"
description = "Number of residential buildings with return period of 100 years"
select = "COUNT(*)"
filter = "`Primary Object Type` IN ('residential') AND `Total Damage (100Y)` > 0"
long_name = "Flooded homes (100Y)"
show_in_metrics_table = "True"

[[queries]]
name = "ImpactedBusinesses2Y"
description = "Number of commercial buildings with return period of 2 years"
select = "COUNT(*)"
filter = "`Primary Object Type` IN ('commercial')  AND `Total Damage (2Y)` > 0"
long_name = "Flooded businesses (2Y)"
show_in_metrics_table = "True"

[[queries]]
name = "ImpactedBusinesses5Y"
description = "Number of commercial buildings with return period of 5 years"
select = "COUNT(*)"
filter = "`Primary Object Type` IN ('commercial')  AND `Total Damage (5Y)` > 0"
long_name = "Flooded businesses (5Y)"
show_in_metrics_table = "True"

[[queries]]
name = "ImpactedBusinesses10Y"
description = "Number of commercial buildings with return period of 10 years"
select = "COUNT(*)"
filter = "`Primary Object Type` IN ('commercial')  AND `Total Damage (10Y)` > 0"
long_name = "Flooded businesses (10Y)"
show_in_metrics_table = "True"

[[queries]]
name = "ImpactedBusinesses25Y"
description = "Number of commercial buildings with return period of 25 years"
select = "COUNT(*)"
filter = "`Primary Object Type` IN ('commercial')  AND `Total Damage (25Y)` > 0"
long_name = "Flooded businesses (25Y)"
show_in_metrics_table = "True"

[[queries]]
name = "ImpactedBusinesses50Y"
description = "Number of commercial buildings with return period of 50 years"
select = "COUNT(*)"
filter = "`Primary Object Type` IN ('commercial')  AND `Total Damage (50Y)` > 0"
long_name = "Flooded businesses (50Y)"
show_in_metrics_table = "True"

[[queries]]
name = "ImpactedBusinesses100Y"
description = "Number of commercial buildings with return period of 100 years"
select = "COUNT(*)"
filter = "`Primary Object Type` IN ('commercial')  AND `Total Damage (100Y)` > 0"
long_name = "Flooded businesses (100Y)"
show_in_metrics_table = "True"
