aggregateBy: []

queries:
  - name: "TotalDamageEvent"
    description: "Total building damage"
    select: "SUM(`Total Damage`)"
    filter: ""
    long_name: "Building damage ($)"
    show_in_metrics_table: "True"

  - name: "ResidentialMinorCount"
    description: "Number of residences with minor damage"
    select: "COUNT(*)"
    filter: "`Primary Object Type` IN ('residential') AND `Inundation Depth` <= 0.25 AND `Total Damage` > 0"
    long_name: "Res buildings w/ minor flooding (#)"
    show_in_metrics_table: "False"

  - name: "ResidentialMajorCount"
    description: "Number of residences with major damage"
    select: "COUNT(*)"
    filter: "`Primary Object Type` IN ('residential') AND `Inundation Depth` <= 1.5 AND `Inundation Depth` > 0.25 AND `Total Damage` > 0"
    long_name: "Res buildings w/ major flooding (#)"
    show_in_metrics_table: "False"

  - name: "ResidentialDestroyedCount"
    description: "Number of destroyed residences"
    select: "COUNT(*)"
    filter: "`Primary Object Type` IN ('residential') AND `Inundation Depth` > 1.5 AND `Total Damage` > 0"
    long_name: "Res buildings destroyed (#)"
    show_in_metrics_table: "False"

  - name: "CommercialMinorCount"
    description: "Number of commercial buildings with minor flooding"
    select: "COUNT(*)"
    filter: "`Secondary Object Type` IN ('commercial')  AND `Inundation Depth` <= 0.25 AND `Total Damage` > 0"
    long_name: "Minor Damaged Commercial Buildings"
    show_in_metrics_table: "False"

  - name: "CommercialMajorCount"
    description: "Number of commercial buildings with major flooding"
    select: "COUNT(*)"
    filter: "`Secondary Object Type` IN ('commercial')  AND `Inundation Depth` <= 1.5 AND `Inundation Depth` > 0.25 AND `Total Damage` > 0"
    long_name: "Major Damaged Commercial Buildings"
    show_in_metrics_table: "False"

  - name: "CommercialDestroyedCount"
    description: "Number of destroyed commercial buildings"
    select: "COUNT(*)"
    filter: "`Secondary Object Type` IN ('commercial')  AND `Inundation Depth` > 1.5 AND `Total Damage` > 0"
    long_name: "Destroyed Commercial Buildings"
    show_in_metrics_table: "False"

  - name: "IndustrialMinorCount"
    description: "Number of industrial buildings with minor flooding"
    select: "COUNT(*)"
    filter: "`Secondary Object Type` IN ('industrial')  AND `Inundation Depth` <= 0.25 AND `Total Damage` > 0"
    long_name: "Minor Damaged Industrial Buildings"
    show_in_metrics_table: "False"

  - name: "IndustrialMajorCount"
    description: "Number of industrial buildings with major flooding"
    select: "COUNT(*)"
    filter: "`Secondary Object Type` IN ('industrial')  AND `Inundation Depth` <= 1.5 AND `Inundation Depth` > 0.25 AND `Total Damage` > 0"
    long_name: "Major Damaged Industrial Buildings"
    show_in_metrics_table: "False"

  - name: "IndustrialDestroyedCount"
    description: "Number of destroyed industrial buildings"
    select: "COUNT(*)"
    filter: "`Secondary Object Type` IN ('industrial')  AND `Inundation Depth` > 1.5 AND `Total Damage` > 0"
    long_name: "Destroyed Industrial Buildings"
    show_in_metrics_table: "False"

  - name: "FloodedHomes"
    description: "Number of flooded homes "
    select: "COUNT(*)"
    filter: "`Primary Object Type` IN ('residential') AND `Inundation Depth` <= 1.5 AND `Total Damage` > 0"
    long_name: "Flooded Homes"
    show_in_metrics_table: "False"

  - name: "DisplacedHomes"
    description: "Number of homes with displaced people"
    select: "COUNT(*)"
    filter: "`Primary Object Type` IN ('residential') AND `Inundation Depth` > 1.5 AND `Total Damage` > 0"
    long_name: "Homes with Displaced People"
    show_in_metrics_table: "False"
