aggregateBy = [ "default_aggregation",]
[[queries]]
name = "MinorFloodedRoads"
description = "Roads disrupted for cars"
select = "SUM(`segment_length`)"
filter = "`inun_depth` >= 0.5"
long_name = "Minor flooded roads"
show_in_metrics_table = "False"

[[queries]]
name = "MajorFloodedRoads"
description = "Roads disrupted for trucks"
select = "SUM(`segment_length`)"
filter = "`inun_depth` >= 1"
long_name = "Major flooded roads"
show_in_metrics_table = "False"

[[queries]]
name = "FullyFloodedRoads"
description = "Roads disrupted for rescue vehicles"
select = "SUM(`segment_length`)"
filter = "`inun_depth` >= 2"
long_name = "Fully flooded roads"
show_in_metrics_table = "True"
