aggregateBy = [ "Neighbourhood",]
[[queries]]
name = "TotalDamageEvent"
description = "Total building damage"
select = "SUM(`Total Damage`)"
filter = ""
long_name = "Building damage (Eur)"
show_in_metrics_table = "True"

[[queries]]
name = "TotalResDamageEvent"
description = "Total residential building damage"
select = "SUM(`Total Damage`)"
filter = "`Primary Object Type` IN ('RES')"
long_name = "Residential building damage ($)"
show_in_metrics_table = "True"

[[queries]]
name = "FloodedAll"
description = "Number of flooded buildings"
select = "COUNT(*)"
filter = "`Primary Object Type` IN ('RES') AND `Total Damage` > 0"
long_name = "Flooded Homes (#)"
show_in_metrics_table = "True"

[[queries]]
name = "CommercialCount"
description = "Number of commercial buildings with flooding"
select = "COUNT(*)"
filter = "`Secondary Object Type` IN ('COM1', 'COM2', 'COM3', 'COM4', 'COM5', 'COM8', 'COM9')  AND `Total Damage` > 0"
long_name = "Flooded businesses (#)"
show_in_metrics_table = "True"
