aggregateBy = [ "Neighbourhood",]
[[queries]]
name = "ExpectedAnnualDamages"
description = "Expected annual damages"
select = "SUM(`ead_damage`)"
filter = ""
long_name = "Expected Annual Damages"
show_in_metrics_table = "True"

[[queries]]
name = "FloodedHomes"
description = "Homes likely to flood (inun_depth > 0.2) in 30 year period"
select = "COUNT(*)"
filter = "`Exceedance Probability` > 50 AND `primary_object_type` IN ('residential')"
long_name = "Homes likely to flood in 30-year period (#)"
show_in_metrics_table = "False"

[[queries]]
name = "TotalDamageRP1"
description = "total_damage with return period of 1 years"
select = "SUM(`total_damage_1.0y`)"
filter = ""
long_name = "total_damage (RP 1)"
show_in_metrics_table = "True"

[[queries]]
name = "TotalDamageRP2"
description = "total_damage with return period of 2 years"
select = "SUM(`total_damage_2.0y`)"
filter = ""
long_name = "total_damage (RP 2)"
show_in_metrics_table = "True"

[[queries]]
name = "TotalDamageRP5"
description = "total_damage with return period of 5 years"
select = "SUM(`total_damage_5.0y`)"
filter = ""
long_name = "total_damage (RP 5)"
show_in_metrics_table = "True"

[[queries]]
name = "TotalDamageRP10"
description = "total_damage with return period of 10 years"
select = "SUM(`total_damage_10.0y`)"
filter = ""
long_name = "total_damage (RP 10)"
show_in_metrics_table = "True"

[[queries]]
name = "TotalDamageRP25"
description = "total_damage with return period of 25 years"
select = "SUM(`total_damage_25.0y`)"
filter = ""
long_name = "total_damage (RP 25)"
show_in_metrics_table = "True"

[[queries]]
name = "TotalDamageRP50"
description = "total_damage with return period of 50 years"
select = "SUM(`total_damage_50.0y`)"
filter = ""
long_name = "total_damage (RP 50)"
show_in_metrics_table = "True"

[[queries]]
name = "TotalDamageRP100"
description = "total_damage with return period of 100 years"
select = "SUM(`total_damage_100.0y`)"
filter = ""
long_name = "total_damage (RP 100)"
show_in_metrics_table = "True"

[[queries]]
name = "FloodedHomes2Y"
description = "Number of flooded residential buildings with return period of 2 years"
select = "COUNT(*)"
filter = "`primary_object_type` IN ('residential') AND `inun_depth_2.0y` > 0.2"
long_name = "Flooded  homes (RP 2)"
show_in_metrics_table = "True"

[[queries]]
name = "FloodedHomes5Y"
description = "Number of flooded residential buildings with return period of 5 years"
select = "COUNT(*)"
filter = "`primary_object_type` IN ('residential') AND `inun_depth_5.0y` > 0.2"
long_name = "Flooded  homes (RP 5)"
show_in_metrics_table = "True"

[[queries]]
name = "FloodedHomes10Y"
description = "Number of flooded residential buildings with return period of 10 years"
select = "COUNT(*)"
filter = "`primary_object_type` IN ('residential') AND `inun_depth_10.0y` > 0.2"
long_name = "Flooded  homes (RP 10)"
show_in_metrics_table = "True"

[[queries]]
name = "FloodedHomes25Y"
description = "Number of flooded residential buildings with return period of 25 years"
select = "COUNT(*)"
filter = "`primary_object_type` IN ('residential') AND `inun_depth_25.0y` > 0.2"
long_name = "Flooded  homes (RP 25)"
show_in_metrics_table = "True"

[[queries]]
name = "FloodedHomes50Y"
description = "Number of flooded residential buildings with return period of 50 years"
select = "COUNT(*)"
filter = "`primary_object_type` IN ('residential') AND `inun_depth_50.0y` > 0.2"
long_name = "Flooded  homes (RP 50)"
show_in_metrics_table = "True"

[[queries]]
name = "FloodedHomes100Y"
description = "Number of flooded residential buildings with return period of 100 years"
select = "COUNT(*)"
filter = "`primary_object_type` IN ('residential') AND `inun_depth_100.0y` > 0.2"
long_name = "Flooded  homes (RP 100)"
show_in_metrics_table = "True"

[[queries]]
name = "FloodedBusinesses2Y"
description = "Number of flooded commercial buildings with return period of 2 years"
select = "COUNT(*)"
filter = "`primary_object_type` IN ('commercial')  AND `inun_depth_2.0y` > 0.2"
long_name = "Flooded  businesses (RP 2)"
show_in_metrics_table = "True"

[[queries]]
name = "FloodedBusinesses5Y"
description = "Number of flooded commercial buildings with return period of 5 years"
select = "COUNT(*)"
filter = "`primary_object_type` IN ('commercial')  AND `inun_depth_5.0y` > 0.2"
long_name = "Flooded  businesses (RP 5)"
show_in_metrics_table = "True"

[[queries]]
name = "FloodedBusinesses10Y"
description = "Number of flooded commercial buildings with return period of 10 years"
select = "COUNT(*)"
filter = "`primary_object_type` IN ('commercial')  AND `inun_depth_10.0y` > 0.2"
long_name = "Flooded  businesses (RP 10)"
show_in_metrics_table = "True"

[[queries]]
name = "FloodedBusinesses25Y"
description = "Number of flooded commercial buildings with return period of 25 years"
select = "COUNT(*)"
filter = "`primary_object_type` IN ('commercial')  AND `inun_depth_25.0y` > 0.2"
long_name = "Flooded  businesses (RP 25)"
show_in_metrics_table = "True"

[[queries]]
name = "FloodedBusinesses50Y"
description = "Number of flooded commercial buildings with return period of 50 years"
select = "COUNT(*)"
filter = "`primary_object_type` IN ('commercial')  AND `inun_depth_50.0y` > 0.2"
long_name = "Flooded  businesses (RP 50)"
show_in_metrics_table = "True"

[[queries]]
name = "FloodedBusinesses100Y"
description = "Number of flooded commercial buildings with return period of 100 years"
select = "COUNT(*)"
filter = "`primary_object_type` IN ('commercial')  AND `inun_depth_100.0y` > 0.2"
long_name = "Flooded  businesses (RP 100)"
show_in_metrics_table = "True"

[[queries]]
name = "FloodedIndustry2Y"
description = "Number of flooded industrial buildings with return period of 2 years"
select = "COUNT(*)"
filter = "`primary_object_type` IN ('industrial') AND `inun_depth_2.0y` > 0.2"
long_name = "Flooded  industry (RP 2)"
show_in_metrics_table = "True"

[[queries]]
name = "FloodedIndustry5Y"
description = "Number of flooded industrial buildings with return period of 5 years"
select = "COUNT(*)"
filter = "`primary_object_type` IN ('industrial') AND `inun_depth_5.0y` > 0.2"
long_name = "Flooded  industry (RP 5)"
show_in_metrics_table = "True"

[[queries]]
name = "FloodedIndustry10Y"
description = "Number of flooded industrial buildings with return period of 10 years"
select = "COUNT(*)"
filter = "`primary_object_type` IN ('industrial') AND `inun_depth_10.0y` > 0.2"
long_name = "Flooded  industry (RP 10)"
show_in_metrics_table = "True"

[[queries]]
name = "FloodedIndustry25Y"
description = "Number of flooded industrial buildings with return period of 25 years"
select = "COUNT(*)"
filter = "`primary_object_type` IN ('industrial') AND `inun_depth_25.0y` > 0.2"
long_name = "Flooded  industry (RP 25)"
show_in_metrics_table = "True"

[[queries]]
name = "FloodedIndustry50Y"
description = "Number of flooded industrial buildings with return period of 50 years"
select = "COUNT(*)"
filter = "`primary_object_type` IN ('industrial') AND `inun_depth_50.0y` > 0.2"
long_name = "Flooded  industry (RP 50)"
show_in_metrics_table = "True"

[[queries]]
name = "FloodedIndustry100Y"
description = "Number of flooded industrial buildings with return period of 100 years"
select = "COUNT(*)"
filter = "`primary_object_type` IN ('industrial') AND `inun_depth_100.0y` > 0.2"
long_name = "Flooded  industry (RP 100)"
show_in_metrics_table = "True"

[flood_exceedance]
column = "inun_depth"
threshold = 0.2
period = 30
