setup_global_settings:
  keep_temp_files: True

setup_output:
  output_dir: output
  output_csv_name: output.csv
  output_vector_name: spatial.gpkg

setup_vulnerability:
  vulnerability_fn: jrc_vulnerability_curves
  vulnerability_identifiers_and_linking_fn: jrc_vulnerability_curves_linking
  unit: m
  continent: South America

setup_exposure_buildings:
  asset_locations: preprocessed_occupaction_jrc
  occupancy_type: preprocessed_occupaction_jrc
  keep_unclassified: True
  max_potential_damage: jrc_damage_values
  ground_floor_height: preprocessed_floor_height
  gfh_attribute_name: altura
  unit: m
  ground_elevation: rio/setups/local/models/sfincs/subgrid/dep_subgrid.tif
  damage_types: [structure, content]
  country: Brazil

setup_exposure_population:
  impacted_population_fn: preprocessed_asset_population
  attribute_name: residents
