setup_global_settings:
  keep_temp_files: True

setup_output:
  output_dir: output
  output_csv_name: output.csv
  output_vector_name: spatial.gpkg

setup_vulnerability_from_csv:
  vulnerability_curves: vulnerability_curves
  vulnerability_identifiers_and_linking_fn: vulnerability_curves_linking
  unit: meters

setup_population_vulnerability:
  vertical_unit: "m" # unit of the inundation depth
  threshold_value: 0.4 # depth at which people would be fully affected
  min_hazard_value: 0
  max_hazard_value: 10 # per building, e.g. 10 people per building
  step_hazard_value: 0.1 # resolution of the damage curve and the interpolation between the values

setup_exposure_buildings:
  asset_locations: preprocessed_occupaction
  occupancy_type: preprocessed_occupaction
  keep_unclassified: True
  max_potential_damage: damage_values
  linking_column: secondary_object_type
  ground_floor_height: preprocessed_floor_height
  gfh_attribute_name: altura
  unit: meters
  ground_elevation: rio/setups/local/models/sfincs/subgrid/dep_subgrid.tif
  damage_types: [structure, content]
  damage_unit: "BRL"
  bf_conversion: True

# setup_exposure_roads:
#   roads_fn: "OSM"
#   road_types: ["motorway", "primary", "secondary", "tertiary"]
#   road_damage: null
#   unit: "meters"

setup_exposure_population:
  impacted_population_fn: preprocessed_asset_population
  attribute_name: residents

setup_aggregation_areas:
  aggregation_area_fn: rio/data/local-data/census/aggregation_neighbourhood.gpkg
  attribute_names: "nm_subdist"
  label_names: "neighbourhood"
  file_names: "census_neighbourhoods"
