# This file was generated by hydroflows version 0.1.0.dev

configfile: "sfincs_pluvial.config.yml"

EVENT=["p_event01", "p_event02", "p_event03"]

rule all:
    input:
        fiat_out="models/fiat/simulations/event_set/output/spatial.gpkg",

rule sfincs_build:
    input:
        region=config["region"],
    params:
        sfincs_root="models/sfincs",
        res=100.0,
    output:
        sfincs_inp="models/sfincs/sfincs.inp",
        sfincs_region="models/sfincs/gis/region.geojson",
        sfincs_subgrid_dep="models/sfincs/subgrid/dep_subgrid.tif",
    shell:
        """
        hydroflows method sfincs_build \
        region="{input.region}" \
        sfincs_root="{params.sfincs_root}" \
        res="{params.res}" \
        """

rule fiat_build:
    input:
        region=rules.sfincs_build.output.sfincs_region,
    params:
        fiat_root="models/fiat",
    output:
        fiat_cfg="models/fiat/settings.toml",
    shell:
        """
        hydroflows method fiat_build \
        region="{input.region}" \
        fiat_root="{params.fiat_root}" \
        """

rule get_ERA5_rainfall:
    input:
        region=rules.sfincs_build.output.sfincs_region,
    output:
        precip_nc="data/input/era5_precip.nc",
    shell:
        """
        hydroflows method get_ERA5_rainfall \
        region="{input.region}" \
        """

rule pluvial_design_events:
    input:
        precip_nc=rules.get_ERA5_rainfall.output.precip_nc,
    params:
        event_root="data/events/rainfall",
        rps=config["rps"],
        event_names=EVENT,
    output:
        event_yaml=expand("data/events/rainfall/{event}.yml", event=EVENT),
        event_csv=expand("data/events/rainfall/{event}.csv", event=EVENT),
        event_set="data/events/rainfall/event_set.yml",
    shell:
        """
        hydroflows method pluvial_design_events \
        precip_nc="{input.precip_nc}" \
        event_root="{params.event_root}" \
        rps="{params.rps}" \
        event_names="{params.event_names}" \
        """

rule sfincs_update_forcing:
    input:
        sfincs_inp=rules.sfincs_build.output.sfincs_inp,
        event_yaml=rules.pluvial_design_events.output.event_yaml,
    params:
        event_name="{event}",
    output:
        sfincs_out_inp="models/sfincs/simulations/{event}/sfincs.inp",
    shell:
        """
        hydroflows method sfincs_update_forcing \
        sfincs_inp="{input.sfincs_inp}" \
        event_yaml="{input.event_yaml}" \
        event_name="{params.event_name}" \
        """

rule sfincs_run:
    input:
        sfincs_inp=rules.sfincs_update_forcing.output.sfincs_out_inp,
    params:
        sfincs_exe=config["sfincs_exe"],
    output:
        sfincs_map="models/sfincs/simulations/{event}/sfincs_map.nc",
    shell:
        """
        hydroflows method sfincs_run \
        sfincs_inp="{input.sfincs_inp}" \
        sfincs_exe="{params.sfincs_exe}" \
        """

rule sfincs_postprocess:
    input:
        sfincs_map=rules.sfincs_run.output.sfincs_map,
        sfincs_subgrid_dep=rules.sfincs_build.output.sfincs_subgrid_dep,
    params:
        hazard_root="data/output/hazard",
        event_name="{event}",
    output:
        hazard_tif="data/output/hazard/{event}.tif",
    shell:
        """
        hydroflows method sfincs_postprocess \
        sfincs_map="{input.sfincs_map}" \
        sfincs_subgrid_dep="{input.sfincs_subgrid_dep}" \
        hazard_root="{params.hazard_root}" \
        event_name="{params.event_name}" \
        """

rule fiat_update_hazard:
    input:
        fiat_cfg=rules.fiat_build.output.fiat_cfg,
        event_set_yaml=rules.pluvial_design_events.output.event_set,
        hazard_maps=expand("data/output/hazard/{event}.tif", event=EVENT),
    output:
        fiat_hazard="models/fiat/simulations/event_set/hazard.nc",
        fiat_out_cfg="models/fiat/simulations/event_set/settings.toml",
    shell:
        """
        hydroflows method fiat_update_hazard \
        fiat_cfg="{input.fiat_cfg}" \
        event_set_yaml="{input.event_set_yaml}" \
        hazard_maps="{input.hazard_maps}" \
        """

rule fiat_run:
    input:
        fiat_cfg=rules.fiat_update_hazard.output.fiat_out_cfg,
    params:
        fiat_bin=config["fiat_exe"],
    output:
        fiat_out="models/fiat/simulations/event_set/output/spatial.gpkg",
    shell:
        """
        hydroflows method fiat_run \
        fiat_cfg="{input.fiat_cfg}" \
        fiat_bin="{params.fiat_bin}" \
        """
