# This file was generated by hydroflows version 0.1.0.dev

configfile: "sfincs_pluvial.config.yml"

EVENT = ["p_event01", "p_event02", "p_event03"]


rule all:
    input:
        expand("data\output\hazard\{event}.tif", event=EVENT),


rule sfincs_build:
    input:
        region=config["region"],
    output:
        sfincs_inp="models\sfincs\sfincs.inp",
        sfincs_region="models\sfincs\gis\region.geojson",
        sfincs_subgrid_dep="models\sfincs\subgrid\dep.tif",
    shell:
        """
        hydroflows method sfincs_build \
        region="{input.region}" \
        """

rule get_ERA5_rainfall:
    input:
        region=rules.sfincs_build.output.sfincs_region,
    output:
        precip_nc="data\input\era5_precip.nc",
    shell:
        """
        hydroflows method get_ERA5_rainfall \
        region="{input.region}" \
        """

rule pluvial_design_events:
    input:
        precip_nc=rules.get_ERA5_rainfall.output.precip_nc,
    params:
        rps=config["rps"],
    output:
        event_yaml=expand("data\events\rainfall\{event}.yml", event=EVENT),
        event_csv=expand("data\events\rainfall\{event}.csv", event=EVENT),
        event_catalog="data\events\rainfall\event_catalog.yml",
    shell:
        """
        hydroflows method pluvial_design_events \
        precip_nc="{input.precip_nc}" \
        rps="{params.rps}" \
        """

rule sfincs_update_forcing:
    input:
        sfincs_inp=rules.sfincs_build.output.sfincs_inp,
        event_yaml=rules.pluvial_design_events.output.event_yaml,
    output:
        sfincs_out_inp="models\sfincs\simulations\{event}\sfincs.inp",
    shell:
        """
        hydroflows method sfincs_update_forcing \
        sfincs_inp="{input.sfincs_inp}" \
        event_yaml="{input.event_yaml}" \
        """

rule sfincs_run:
    input:
        sfincs_inp=rules.sfincs_update_forcing.output.sfincs_out_inp,
    params:
        sfincs_exe=config["sfincs_exe"],
    output:
        sfincs_map="models\sfincs\simulations\{event}\sfincs_map.nc",
    shell:
        """
        hydroflows method sfincs_run \
        sfincs_inp="{input.sfincs_inp}" \
        sfincs_exe="{params.sfincs_exe}" \
        """

rule sfincs_postprocess:
    input:
        sfincs_map=rules.sfincs_run.output.sfincs_map,
        sfincs_subgrid_dep="models\sfincs\subgrid\dep.tif",
    output:
        hazard_tif="data\output\hazard\{event}.tif",
    shell:
        """
        hydroflows method sfincs_postprocess \
        sfincs_map="{input.sfincs_map}" \
        """
