"""Downscale climate data method."""

from pathlib import Path

import hydromt  # noqa: F401
import xarray as xr

from hydroflows.methods.climate.utils import to_netcdf
from hydroflows.workflow.method import Method
from hydroflows.workflow.method_parameters import Parameters


class Input(Parameters):
    """Input parameters.

    This class represents the input data
    required for the :py:class:`DownscaleClimateDataset` method.
    """

    dataset: Path
    """The path to the to be downscaled dataset."""

    ds_like: Path
    """
    The dataset with the desired resolution.
    """


class Output(Parameters):
    """output parameters.

    this class represents the output data
    generated by the :py:class:`DownscaleClimateDataset` method.
    """

    downscaled: Path
    """Path to the downscaled dataset."""


class Params(Parameters):
    """Parameters for the :py:class:`DownscaleClimateDataset`.

    Instances of this class are used in the :py:class:`DownscaleClimateDataset`
    method to define the required settings.
    """

    data_root: Path
    """
    The output directory of the dataset.
    """

    resample_method: str = "nearest"
    """Method of resampling the low(er) res dataset."""


class DownscaleClimateDataset(Method):
    """Method to downscale climate change factor dataset."""

    name: str = "downscale_climate_datasets"

    _test_kwargs = {
        "dataset": Path("dataset.nc"),
        "ds_like": Path("ds_like.nc"),
        "data_root": Path("data"),
    }

    def __init__(
        self,
        dataset: Path,
        ds_like: Path,
        **params,
    ):
        """Downscale a dataset to the resolution of another dataset.

        Parameters
        ----------
        dataset : Path
            Path to the to be downscaled dataset.
        ds_like : Path
            Path to the dataset with the target resolution.
        **params
            Additional parameters to pass to the DownscaleClimateDataset instance.
            See :py:class:`downscale Params <hydroflows.methods.climate.downscale.Params>`.

        See Also
        --------
        :py:class:`downscale Input <~hydroflows.methods.climate.downscale.Input>`
        :py:class:`downscale Output <~hydroflows.methods.climate.downscale.Output>`
        :py:class:`downscale Params <~hydroflows.methods.climate.downscale.Params>`
        """
        self.params: Params = Params(**params)
        self.input: Input = Input(dataset=dataset, ds_like=ds_like)
        fname = self.input.dataset.stem
        fsuffix = self.input.dataset.suffix
        self.output: Output = Output(
            downscaled=self.params.data_root / f"{fname}_downscaled{fsuffix}"
        )

    def run(self):
        """Run the downscale dataset method."""
        # open datasets
        ds = xr.open_dataset(self.input.dataset, lock=False)
        # Open dst_grid similar to WflowModel.read_grid
        ds_like = xr.open_dataset(
            self.input.ds_like, mask_and_scale=False, decode_coords="all"
        ).load()
        ds_like.close()
        # make sure maps are always North -> South oriented for hydromt
        if ds_like.raster.res[1] > 0:
            ds_like = ds_like.raster.flipud()

        # squeeze
        ds = ds.squeeze()

        # convert from percentage to fraction for variables that are not temperature
        for var in ds.data_vars:
            if not var.startswith("temp"):
                ds[var] = 1 + ds[var] / 100

        ds_downscaled = ds.raster.reproject_like(
            ds_like,
            method=self.params.resample_method,
        )

        # rename from month to time for wflow
        if "month" in ds_downscaled.coords:
            ds_downscaled = ds_downscaled.rename({"month": "time"})

        # write netcdf
        to_netcdf(
            ds_downscaled,
            file_name=self.output.downscaled.name,
            output_dir=self.params.data_root,
        )
