"""Blabla."""

from pathlib import Path

from hydroflows._typing import ListOfPath
from hydroflows.workflow.method import ReduceMethod
from hydroflows.workflow.method_parameters import Parameters


class Input(Parameters):
    """Input parameters.

    This class represents the input data
    required for the :py:class:`ClimateStatistics` method.
    """

    datasets: ListOfPath | Path
    """The path(s) to the datasets of the different climate models."""


class Output(Parameters):
    """output parameters.

    this class represents the output data
    generated by the :py:class:`climatefactorsgridded` method.
    """

    merged: Path
    """Path to the single output merged dataset."""


class Params(Parameters):
    """Parameters for the :py:class:`ClimateFactorsGridded`.

    Instances of this class are used in the :py:class:`Rainfall`
    method to define the required settings.
    """

    scenario: str
    """
    The specific climate scenario. Chose from ... # TODO
    """

    how: str = "mean"
    """"""

    data_root: Path
    """
    The output directory of the dataset.
    """


class MergeDatasets(ReduceMethod):
    """Method to merge datasets of different climate models."""

    name: str = "merge_datasets"

    _test_kwargs = {}

    def __init__(
        self,
        ds_in: list,
        **params,
    ):
        self.params: Params = Params(**params)
        self.input: Input = Input(ds_in=ds_in)
        self.output: Output = Output(
            ds_out=self.params.data_root / f"{self.params.scenario}_factors.nc"
        )

        pass

    def run(self):
        """Run the merge datasets method."""
        pass
