"""SFINCS run method."""

import platform
import subprocess
from pathlib import Path
from typing import Literal, Optional

from pydantic import BaseModel

from hydroflows.methods.method import Method

__all__ = ["SfincsRun"]


class Input(BaseModel):
    """Input parameters.

    This class represents the input data
    required for the :py:class:`SfincsRun` method.
    """

    sfincs_inp: Path
    """The path to the SFINCS model configuration (inp) file."""


class Output(BaseModel):
    """Output parameters.

    This class represents the output data
    generated by the :py:class:`SfincsRun` method.
    """

    sfincs_map: Path
    """The path to the SFINCS sfincs_map.nc output file."""


class Params(BaseModel):
    """Parameters.

    Instances of this class are used in the :py:class:`SfincsRun`
    method to define the required settings.
    """

    sfincs_exe: Optional[Path] = None
    """The path to SFINCS executable."""

    vm: Optional[Literal["docker", "singularity"]] = None
    """The virtual machine environment to use."""

    docker_tag: str = "latest"
    """The Docker tag to specify the version of the Docker image to use."""


class SfincsRun(Method):
    """Rule for running a Sfincs model."""

    name: str = "sfincs_run"

    def __init__(self, sfincs_inp: str, **params) -> "SfincsRun":
        """Create and validate a sfincs_run instance.

        Parameters
        ----------
        sfincs_inp : str
            Path to the SFINCS input file.
        **params
            Additional parameters to pass to the SfincsRun instance.
            See :py:class:`sfincs_run Params <hydroflows.methods.sfincs.sfincs_run.Params>`.

        See Also
        --------
        :py:class:`sfincs_run Input <hydroflows.methods.sfincs.sfincs_run.Input>`
        :py:class:`sfincs_run Output <hydroflows.methods.sfincs.sfincs_run.Output>`
        :py:class:`sfincs_run Params <hydroflows.methods.sfincs.sfincs_run.Params>`
        """
        self.params: Params = Params(**params)
        self.input: Input = Input(sfincs_inp=sfincs_inp)
        self.output: Output = Output(
            sfincs_map=Path(sfincs_inp).parent / "sfincs_map.nc"
        )

    def run(self) -> None:
        """Run the SfincsRun method."""
        # check if the input files and the output directory exist
        self.check_input_output_paths()

        # make sure model_root is an absolute path
        model_root = self.input.sfincs_inp.parent.resolve()

        # set command to run depending on OS and VM
        if self.params.sfincs_exe is not None and platform.system() == "Windows":
            sfincs_exe = self.params.sfincs_exe.resolve()
            if not sfincs_exe.is_file():
                raise FileNotFoundError(f"sfincs_exe not found: {sfincs_exe}")
            cmd = [str(sfincs_exe)]
        elif self.params.vm is not None:
            vm = self.params.vm
            docker_tag = self.params.docker_tag
            if vm == "docker":
                cmd = [
                    "docker",
                    "run",
                    f"-v{model_root}://data",
                    f"deltares/sfincs-cpu:{docker_tag}",
                ]
            elif vm == "singularity":
                cmd = [
                    "singularity",
                    "run",
                    f"-B{model_root}:/data",
                    "--nv",
                    f"docker://deltares/sfincs-cpu:{docker_tag}",
                ]
        else:
            if platform.system() == "Windows":
                raise ValueError("sfince_exe must be specified for Windows")
            else:
                raise ValueError("vm must be specified for Linux or macOS")

        # run & write log file
        log_file = model_root / "sfincs_log.txt"
        with open(log_file, "w") as f:
            proc = subprocess.run(
                cmd,
                cwd=model_root,
                stdout=f,
                stderr=f,
            )
            return_code = proc.returncode

        # check return code
        if self.params.vm is not None and return_code == 127:
            raise RuntimeError(
                f"{vm} not found. Make sure it is installed, running and added to PATH."
            )
        elif return_code != 0:
            raise RuntimeError(f"SFINCS run failed with return code {return_code}")

        # check if "Simulation stopped" in log file
        with open(log_file, "r") as f:
            log = f.read()
            if "Simulation stopped" in log:
                raise RuntimeError(
                    f"SFINCS run failed. Check log file for details: {log_file}"
                )

        return None
