setup_output: 
  output_dir: "output"
  output_csv_name: "output.csv"
  output_vector_name: "spatial.gpkg"

setup_vulnerability:
  vulnerability_fn: "data/damage_curves/df_vulnerability.csv"
  vulnerability_identifiers_and_linking_fn: "data/damage_curves/linking_file.csv"
  unit: "m"

setup_exposure_buildings:
  asset_locations: "data/occupancy/occupancy_pre_processed_translated_occupaction_local_dummy.gpkg"
  occupancy_type: "data/occupancy/occupancy_pre_processed_translated_occupaction_local_dummy.gpkg"
  keep_unclassified: False
  max_potential_damage: "data/damage_curves/base_damage_values.csv"
  ground_floor_height: "data/finished_floor_height/finished_floor_height.gpkg"
  gfh_attribute_name: "altura"
  unit: "m"
  damage_types: ["structure", "content"]
  damage_translation_fn: "data/damage_curves/damage_translation.csv"

setup_exposure_population:
  impacted_population_fn: "data/population/asset_population.gpkg" 
  attribute_name: "residents"
