"""Build a FIAT model from scratch using hydromt_fiat."""

import logging
from pathlib import Path
from typing import Optional

from hydromt import log
from hydromt.writers import write_yaml
from hydromt_fiat import FIATModel
from hydromt_fiat.data import fetch_data
from workflowpy._typing import FileDirPath, ListOfStr
from workflowpy.method import Method
from workflowpy.parameters import Parameters

from hydroflows.cfg import CFG_DIR, read_recipe

__all__ = ["FIATBuild", "Input", "Output", "Params"]


class Input(Parameters):
    """Input parameters.

    This class represents the input data
    required for the :py:class:`FIATBuild` method.
    """

    region: Path
    """
    The file path to the geometry file that defines the region of interest
    for constructing a FIAT model.
    """

    config: Path = CFG_DIR / "fiat_build.yml"
    """The path to the configuration file (.yml) that defines the settings
    to build a FIAT model. In this file the different model components
    that are required by the :py:class:`hydromt_fiat.fiat.FiatModel` are listed.
    Every component defines the setting for each hydromt_fiat setup methods.
    For more information see hydromt_fiat method
    `documentation <https://deltares.github.io/hydromt_fiat/latest/user_guide/user_guide_overview.html>`_."""

    catalog_path: Optional[FileDirPath] = None
    """The file path to the data catalog. This is a file in yml format, which should contain the data sources specified in the config file."""


class Output(Parameters):
    """Output parameters.

    This class represents the output data
    generated by the :py:class:`FIATBuild` method.
    """

    fiat_cfg: FileDirPath
    """The file path to the FIAT configuration (toml) file."""


class Params(Parameters):
    """Parameters for the :py:class:`FIATBuild`.

    Instances of this class are used in the :py:class:`FIATBuild`
    method to define the required settings.

    See Also
    --------
    :py:class:`hydromt_fiat.fiat.FiatModel`
        For more details on the FiatModel used in hydromt_fiat.
    """

    model_root: Path
    """The path to the root directory where the FIAT model will be created."""

    predefined_catalogs: Optional[ListOfStr] = None
    """List of predefined data catalogs containing the data sources specified in the config file."""


class FIATBuild(Method):
    """Build a FIAT model from scratch using hydromt_fiat.

    Parameters
    ----------
    region : Path
        The file path to the geometry file that defines the region of interest
        for constructing a FIAT model.
    config : Path
        The path to the configuration file (.yml) that defines the settings
        to build a FIAT model. In this file the different model components
        that are required by the :py:class:`hydromt_fiat.fiat.FiatModel` are listed.
    catalog_path: Optional[Path], optional
        The path to the data catalog file (.yml) that contains the data sources
        specified in the config file. If None (default), a predefined data catalog
        should be provided.
    predefined_catalogs : Optional[ListOfStr], optional
        A list containing the predefined data catalog names.
    model_root : Path
        The path to the root directory where the FIAT model will be created,
        by default "models/fiat".
    **params
        Additional parameters to pass to the FIATBuild instance.
        See :py:class:`fiat_build Params <hydroflows.fiat.sfincs_build.Params>`.

    See Also
    --------
    :py:class:`fiat_build Input <~hydroflows.fiat.fiat_build.Input>`
    :py:class:`fiat_build Output <~hydroflows.fiat.fiat_build.Output>`
    :py:class:`fiat_build Params <~hydroflows.fiat.fiat_build.Params>`
    :py:class:`hydromt_fiat.fiat.FIATModel`
    """

    name: str = "fiat_build"

    _test_kwargs = {
        "region": Path("region.geojson"),
        "config": Path("hydroflows/cfg/fiat_build.yml"),
        "predefined_catalogs": ["artifact_data"],
    }

    def __init__(
        self,
        region: Path,
        config: Path,
        catalog_path: Optional[Path] = None,
        predefined_catalogs: Optional[ListOfStr] = None,
        model_root: Path = Path("models/fiat"),
        **params,
    ) -> None:
        self.params: Params = Params(
            model_root=model_root, predefined_catalogs=predefined_catalogs, **params
        )
        self.input: Input = Input(
            region=region,
            config=config,
            catalog_path=catalog_path,
        )
        if not self.input.catalog_path and not self.params.predefined_catalogs:
            raise ValueError(
                "A data catalog must be specified either via catalog_path or predefined_catalogs."
            )
        self.output: Output = Output(
            fiat_cfg=self.params.model_root / "settings.toml",
        )

    def _run(self):
        """Run the FIATBuild method."""
        log.initialize_logging(
            file_path=Path(self.params.model_root, "hydromt.log"),
            level=logging.INFO,
        )
        global_data = fetch_data("global-data")
        # Read template config
        _, _, steps = read_recipe(
            self.input.config,
            settings={"region": self.input.region},
        )

        data_libs = [Path(global_data, "data_catalog.yml")]
        if self.params.predefined_catalogs:
            data_libs += self.params.predefined_catalogs
        if self.input.catalog_path:
            data_libs += [self.input.catalog_path]

        model = FIATModel(
            root=self.params.model_root,
            mode="w+",
            data_libs=data_libs,
        )

        # Build the model
        model.build(
            steps=steps,
            write=True,
        )

        # Write opt as yaml
        write_yaml(self.params.model_root / "fiat_build.yaml", {"steps": steps})
