"""Method for running a FIAT model."""

import subprocess
from pathlib import Path
from typing import Literal, Optional

from pydantic import model_validator
from workflowpy._typing import FileDirPath
from workflowpy.method import Method
from workflowpy.parameters import Parameters


class Input(Parameters):
    """Input parameters.

    This class represents the input data
    required for the :py:class:`FIATRun` method.
    """

    # fiat_hazard: Path
    # """The path to the FIAT hazard or risk (NetCDF) file."""

    fiat_cfg: FileDirPath
    """The file path to the FIAT configuration (toml) file from the
    FIAT model that needs to be run."""


class Output(Parameters):
    """Output parameters.

    This class represents the output data
    generated by the :py:class:`FIATRun` method.
    """

    fiat_out_gpkg: FileDirPath
    """The resulting spatial file from the fiat calculations."""


class Params(Parameters):
    """Parameters.

    Instances of this class are used in the :py:class:`FIATRun`
    method to define the required settings.
    """

    run_method: Literal["bin", "python"] = "bin"
    """How to run the FIAT model. Options are 'bin' for running binary directly,
    'python' for running the model in a Python environment."""

    fiat_bin: Optional[Path] = None
    """The path to the FIAT binary."""

    threads: int = 1
    """The number of the threads to be used."""

    @model_validator(mode="after")
    def check_fiat_bin(self):
        """Check the FIAT binary path."""
        if self.run_method == "bin" and self.fiat_bin is None:
            raise ValueError("FIAT binary path is required when run_method is 'bin'.")
        return self


class FIATRun(Method):
    """Method for running a FIAT model.

    Parameters
    ----------
    fiat_cfg : Path
        Path to the FIAT config file.
    run_method : Literal["bin", "python"]
        How to run the FIAT model. Options are 'bin' for running the binary directly,
        'python' for running the model in a Python environment.
    fiat_bin : Path
        Path to the FIAT binary. Required if run_method is "bin".
    **params
        Additional parameters to pass to the FIATRun instance.
        See :py:class:`fiat_run Params <hydroflows.fiat.fiat_run.Params>`.

    See Also
    --------
    :py:class:`fiat_run Input <hydroflows.fiat.fiat_run.Input>`
    :py:class:`fiat_run Output <hydroflows.fiat.fiat_run.Output>`
    :py:class:`fiat_run Params <hydroflows.fiat.fiat_run.Params>`
    """

    name: str = "fiat_run"

    _test_kwargs = {
        "fiat_cfg": Path("fiat.toml"),
        "fiat_bin": Path("fiat.exe"),
    }

    def __init__(
        self,
        fiat_cfg: Path,
        run_method: Literal["bin", "python"] = "bin",
        fiat_bin: Optional[Path] = None,
        **params,
    ):
        self.params: Params = Params(fiat_bin=fiat_bin, run_method=run_method, **params)
        self.input: Input = Input(fiat_cfg=fiat_cfg)
        self.output: Output = Output(
            fiat_out_gpkg=self.input.fiat_cfg.parent / "output" / "spatial.gpkg",
        )

        # TODO check if cfg matches output

    def _run(self):
        """Run the FIATRun method."""
        # Get basic info
        cwd = self.input.fiat_cfg.parent
        fiat_cfg_path = self.input.fiat_cfg.name

        entrypoint = (
            "fiat" if self.params.run_method == "python" else str(self.params.fiat_bin)
        )

        # Setup the cli command
        command = [
            entrypoint,
            "run",
            fiat_cfg_path,
            "-t",
            str(self.params.threads),
        ]

        # Execute the rule
        subprocess.run(command, check=True, cwd=cwd)
