"""Wflow build method."""

from pathlib import Path
from typing import Optional

from hydromt.config import configread, configwrite
from hydromt.log import setuplog
from hydromt_wflow import WflowModel
from pydantic import BaseModel, FilePath

from hydroflows._typing import ListOfStr
from hydroflows.methods.method import HYDROMT_CONFIG_DIR, Method
from hydroflows.methods.wflow.wflow_utils import plot_basemap

__all__ = ["WflowBuild"]


class Input(BaseModel):
    """Input parameters.

    This class represents the input data
    required for the :py:class:`WflowBuild` method.
    """

    region: FilePath
    """
    The file path to the geometry file that defines the region of interest
    for constructing a Wflow model for the upstream area draining into
    the specified region. An example of such a file could be the Sfincs region GeoJSON.
    """


class Output(BaseModel):
    """Output parameters.

    This class represents the output data
    generated by the :py:class:`WflowBuild` method.
    """

    wflow_toml: Path
    """
    The file path to the Wflow (toml) configuration file.
    """


class Params(BaseModel):
    """Parameters.

    Instances of this class are used in the :py:class:`WflowBuild`
    method to define the required settings.

    See Also
    --------
    :py:class:`hydromt_wflow.WflowModel`
        For more details on the WflowModel used in hydromt_wflow.
    """

    config: Path = Path(HYDROMT_CONFIG_DIR, "wflow_build.yaml")
    """The path to the configuration file (.yml) that defines the settings
    to build a Wflow model. In this file the different model components
    that are required by the :py:class:`hydromt_wflow.WflowModel` are listed.
    Every component defines the setting for each hydromt_wflow setup methods.
    For more information see hydromt_wflow method
    `documentation <https://deltares.github.io/hydromt_wflow/latest/user_guide/wflow_model_setup.html#model-methods>`_
    """

    data_libs: ListOfStr = ["artifact_data"]
    """List of data libraries to be used. This is a predefined data catalog in
    yml format, which should contain the data sources specified in the config file.
    """

    gauges: Optional[Path] = None
    """Gauges vector file including the locations of interest to get Wflow simulation outputs.
    The vector file must include a column named 'index' that contains the gauge numbers.
    An example of this vector file is the Sfincs source points GeoJSON, which is necessary
    for coupling Wflow with Sfincs to run, for example, a fluvial flood risk assessment workflow.
    """

    upstream_area: int = 30
    """
    Subbasin filter to define rivers based on streams with
    a minimum drainage area in km$^2$.
    """

    plot_fig: bool = True
    """Determines whether to plot a figure with the
    derived Wflow base maps.
    """


class WflowBuild(Method):
    """Rule for building Wflow for the upstream area of the Sfincs boundaries.

    This class utilizes the :py:class:`Params <hydroflows.methods.wflow.wflow_build.Params>`,
    :py:class:`Input <hydroflows.methods.wflow.wflow_build.Input>`, and
    :py:class:`Output <hydroflows.methods.wflow.wflow_build.Output>` classes to build
    a Wflow model.
    """

    name: str = "wflow_build"
    params: Params = Params()  # optional parameters
    input: Input
    output: Output

    def run(self):
        """Run the WflowBuild method."""
        logger = setuplog("build", log_level=20)

        # create the hydromt model
        root = self.output.wflow_toml.parent
        w = WflowModel(
            root=root,
            mode="w+",
            config_fn=self.output.wflow_toml.name,
            data_libs=self.params.data_libs,
            logger=logger,
        )

        # specify region
        region = {
            "subbasin": str(self.input.region),
            "uparea": self.params.upstream_area,
        }

        # read the configuration
        opt = configread(self.params.config)

        # update placeholders in the config
        opt["setup_basemaps"].update(region=region)
        opt["setup_rivers"].update(river_upa=self.params.upstream_area)

        # for reservoirs, lakes and glaciers: check if data is available
        for key in ["reservoirs", "lakes", "glaciers"]:
            if opt[f"setup_{key}"].get(f"{key}_fn") not in w.data_catalog.sources:
                opt.pop(f"setup_{key}")

        # chech whether the sfincs src file was generated
        gauges = self.params.gauges
        if gauges is None or not gauges.is_file():  # remove placeholder
            opt.pop("setup_gauges")
            opt.pop("setup_config_output_timeseries")
        else:  # replace placeholder with actual file
            opt["setup_gauges"]["gauges_fn"] = str(gauges)

        # build the model
        w.build(opt=opt)

        # write the configuration
        configwrite(root / "wflow_build.yaml", opt)

        # plot basemap
        if self.params.plot_fig:
            _ = plot_basemap(w, fn_out="wflow_basemap.png")
