---
name: Build Documentation

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docs:
    defaults:
      run:
        shell: bash -l {0}
    permissions:
      pages: write
      id-token: write
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: "v0.30.0"
          environments: doc
          frozen: true
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      # dummy docs (not IO)
      - name: Generate dummy docs
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          pixi run --frozen -e docs docs-dummy

      # build docs and save to html
      - name: Build docs
        if : ${{ github.event_name != 'pull_request' }}
        run: |
          pixi run --frozen -e doc docs
          echo "DOC_VERSION=$(pixi run --frozen -e doc get-version')" >> $GITHUB_ENV

      # Upload the html docs as an artifact
      - name: Upload artifact
        if : ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/_build/html

      # Deploy the docs to GitHub Pages
      - name: Deploy to GitHub Pages
        if : ${{ github.event_name != 'pull_request' }}
        id: deployment
        uses: actions/deploy-pages@v2
