---
name: Build Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docs:
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11"]
        include:
          - os: ubuntu-latest
            label: linux-64
            prefix: /usr/share/miniconda3/envs/fiat_test

    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        id: python_version
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: pyproject.toml

      - name: Cache hit
        run: echo '${{ steps.python_version.outputs.cache-hit }}'

      - name: Install HydroFlows
        run: |
          pip install --upgrade pip
          pip install .[doc]

      - name: Setup quarto
        run: |
          sudo apt install -y curl
          sudo apt install -y gdebi-core
          mkdir tmp
          curl -L https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.450/quarto-1.3.450-linux-amd64.deb --output tmp/quarto.deb
          chmod +x tmp/quarto.deb
          sudo gdebi -n tmp/quarto.deb

      - name: Install quarto extensions
        run: |
          sudo apt install -y expect
          cd docs
          chmod u+x add_packages.sh
          ./add_packages.sh

      - name: Setup api
        run: |
          cd docs
          python api.py
          python -m quartodoc interlinks

      - name: Generate docs
        run: |
          export PATH=/usr/share/miniconda3/bin:$PATH
          source /usr/share/miniconda3/etc/profile.d/conda.sh
          conda activate fiat_docs
          quarto render docs/ --execute
          echo "DOC_VERSION=$(mamba run -n fiat_docs python -c 'from fiat import __version__ as v; print("dev" if "dev" in v else "v"+v.replace(".dev",""))')" >> $GITHUB_ENV

      - name: Upload to GitHub Pages
        if: ${{ github.event_name != 'pull_request' && !github.event.act }}
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_site
          destination_dir: ./${{ env.DOC_VERSION }}
          keep_files: false
          full_commit_message: Deploy ${{ env.DOC_VERSION }} to GitHub Pages
