name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'tests/**'
      - 'hydroflows/**'
      - '.github/workflows/tests_pixi.yml'
      - pyproject.toml
      - pixi.lock
  pull_request:
    branches:
      - main
    paths:
      - 'tests/**'
      - 'hydroflows/**'
      - '.github/workflows/tests_pixi.yml'
      - pyproject.toml
      - pixi.lock

jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['311'] # ['310']
    runs-on: ${{ matrix.os }}
    name: py ${{ matrix.python-version }} on ${{ matrix.os }}
    timeout-minutes: 30
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.os }}-${{ matrix.python-version }}-${{ github.ref }}
      cancel-in-progress: true

    steps:

      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.3
        with:
          pixi-version: "v0.39.2"
          environments: test-py${{ matrix.python-version }}
          locked: false
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      - name: Restore cache of hydroflows test data
        uses: actions/cache@v4
        id: restore-cache
        with:
          path: ~/.cache/hydroflows/*.tar.gz
          key: test-data-${{ hashFiles('hydroflows/utils/registry.json') }}

      # run test
      - name: Test
        run: pixi run -e test-py${{ matrix.python-version }} test-not-slow
