name: Tests with pip install

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        id: py310
        with:
          python-version: '3.10'
          # caching, see https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
          cache: 'pip'
          cache-dependency-path: pyproject.toml

      # true if cache-hit occurred on the primary key
      - name: Cache hit
        run: echo '${{ steps.py310.outputs.cache-hit }}'

      # build environment with pip
      - name: Install hydroflows
        run: |
          pip install --upgrade pip
          pip install .[test]

      # run test
      - name: Test
        run: |
          python -m pytest -m "not requires_data" --verbose -k "not test_fiat"
